# -*- coding: utf-8 -*-
# @Author: ZwEin
# @Date:   2016-07-09 10:58:11
# @Last Modified by:   ZwEin
# @Last Modified time: 2016-07-11 11:21:52

import pygtrie

def load_trie_obj(trie_obj, words):
    for word in words:
        trie_obj[word] = word
    return trie_obj

def match_names(word, trie_obj):
    word = word.strip().lower()
    if trie_obj.has_key(word):
        return True
    return False

if __name__ == '__main__':

    test_word = 'white'

    words = [
        "whitewright",
        "musselwhite",
        "east white oak",
        "white sands beach estates",
        "whitesmith",
        "white's bridge",
        "whitehouse lower",
        "white marsh",
        "whites bay",
        "white house",
        "whitewall corner",
        "whitehall mobile home park",
        "whitewell",
        "whitebank",
        "white field",
        "whiteford center",
        "white landing",
        "whites road",
        "whites gap",
        "ralphwhite ford (historical)",
        "whitehall landing",
        "white willow",
        "white barn country club",
        "whiteheads mill (historical)",
        "whites",
        "whitehouse forks",
        "white meadow lake",
        "white stick (historical)",
        "whites bluff",
        "olde whitehall",
        "joe whites",
        "white sulphur",
        "whitemark",
        "white settlement",
        "white pine lodge",
        "white spring",
        "whites pond crossroad",
        "white oak estates",
        "whiterocks",
        "glen white",
        "whites cove",
        "white sulphur (historical)",
        "white fox",
        "white mipango",
        "white crystal beach",
        "white church",
        "whitestone estates",
        "white oaks mobile home park",
        "whitehorse estates",
        "white oak landing",
        "glen white junction (historical)",
        "whiteland cross roads",
        "white way subdivision",
        "white cottage",
        "white post",
        "white signal",
        "white rock",
        "white sands estate mobile home park",
        "white chapel",
        "whitehead",
        "big whiteshell lake",
        "white forest",
        "white bluff corssroads",
        "whitestown cross roads",
        "white oak forest",
        "white hill",
        "whitepine",
        "white sands",
        "the estates at whitemarsh hills",
        "whitekirk",
        "white lakes mobile home park",
        "white marsh station",
        "white top",
        "whites settlement",
        "whitener",
        "white water census designated place",
        "whitesides corner",
        "whiteoak grove",
        "whitehaven",
        "white heath",
        "whites landing",
        "white notley",
        "whites city",
        "white pine city (historical)",
        "white mountain lake",
        "white cross",
        "white road (historical)",
        "white elk",
        "white oak village",
        "whiteflat",
        "white waltham",
        "whites crossing",
        "white swamp",
        "white patch",
        "white villa",
        "white pond",
        "white mill",
        "white mobile home park",
        "white elm",
        "whitesburg",
        "white house beach mobile home park",
        "white mountain",
        "white industrial",
        "white sulphur station (historical)",
        "white sulpher (historical)",
        "lower white oak",
        "white swan mobile home park",
        "white briar",
        "whitemarsh woods",
        "whites corner",
        "whitebrook",
        "whitecross",
        "white oak valley",
        "white mill crossing",
        "rosewhite",
        "white horse rapids",
        "whitedog",
        "whitefarland",
        "white city (historical)",
        "white oak bluff",
        "white pine haven",
        "whiteheads creek",
        "the estates at white trout lake",
        "whitebog",
        "white point landing",
        "white spruce",
        "cappawhite",
        "white mwika",
        "whitesides mill",
        "whiteson",
        "white rock acres",
        "bob white farms",
        "white beach",
        "whiteparish",
        "white wolf",
        "white",
        "whitesand",
        "white cone",
        "white point beach",
        "white estates",
        "white oak",
        "white valley",
        "white branch",
        "white gate cross roads",
        "whitehall village",
        "whiteman air force base",
        "whitehall crossroads",
        "white bear lake",
        "whites creek (historical)",
        "white chimneys",
        "white center",
        "montgomery white sulphur springs (historical)",
        "whitesburg estates",
        "whitehouse (historical)",
        "white sand",
        "white owl landing",
        "whitehall acres",
        "seymourstown white",
        "whitehall estate",
        "white gates",
        "white haven trailer park",
        "white birch estates",
        "whitesides estates",
        "whitesville (historical)",
        "whiteinch",
        "white hall fields",
        "big white ski",
        "whitefish hill rv and mobile home park",
        "white trout manor",
        "whites ford",
        "whitehall shores",
        "white oaks estates",
        "white point",
        "white springs",
        "whiteside",
        "whiteoak (historical)",
        "white bead",
        "white stocking",
        "whitehead hill",
        "east white bluffs",
        "white swan lake",
        "white willow (historical)",
        "whitehall forest estates",
        "white oak mobile home park",
        "white island shores",
        "whitehurst landing",
        "whitefish",
        "white river junction",
        "white caps (historical)",
        "whiteman creek",
        "white gardens",
        "ellawhite",
        "whites lake",
        "whitewater pines",
        "white heather",
        "whitetown",
        "white fern",
        "white eyes town (historical)",
        "white rock (historical)",
        "white hall forest",
        "white mound",
        "white cliffs",
        "white oak heights",
        "whitecairns",
        "white gull",
        "southfield at whitemarsh",
        "whitecourt",
        "white house landing",
        "white sands beach",
        "whites hill",
        "white rock curve village",
        "white river",
        "whitesbog",
        "white birch mobile home park",
        "white church place",
        "white oak swamp",
        "whiteport",
        "white iron",
        "white oak junction",
        "white water",
        "white oak corner",
        "white creek",
        "white pine village",
        "white ash",
        "white star",
        "whitebeech",
        "white clay",
        "ingeniero white",
        "white pines",
        "white oak ridge",
        "whitestone logging camp",
        "white deer",
        "white oak springs",
        "white mesa",
        "white oaks",
        "whitehills",
        "whites beach",
        "whitegate",
        "whitecloud",
        "white well",
        "whiteface landing",
        "white lakes (historical)",
        "whitetop",
        "whitecorn",
        "white run",
        "whites valley",
        "whitehorns thicket",
        "white signboard crossroad",
        "lake white mobile home park",
        "marie white subdivision",
        "white hall terrace",
        "white hills mobile home park",
        "white birch village mobile home park",
        "white birch lakes",
        "white house (historical)",
        "white cap",
        "whitewing colonia",
        "west whiteland",
        "white bridge",
        "whitefish point",
        "south whitehall",
        "white pigeon",
        "whiteshop estates",
        "whitehorse farms",
        "whites way",
        "whitehouse crossing",
        "new whiteland",
        "white birches",
        "jack white's cross roads",
        "white owl",
        "whitewater woods",
        "camp bob white",
        "whitemarsh hunt",
        "white oak hills",
        "whiteford",
        "white hills outstation",
        "white kitchen",
        "white stone springs (historical)",
        "whites chapel",
        "white school corner",
        "whiteriver",
        "white mesa village",
        "white circle",
        "whitehall beach",
        "white hills",
        "white's mobile home park",
        "inglewhite",
        "whitehorse",
        "white pines mobile home park",
        "estates at whitemarsh",
        "whitefield",
        "whitetail",
        "whitestar",
        "white river summer home tract",
        "white eye",
        "white tanks",
        "white lake city (historical)",
        "white bluff",
        "whitechapel",
        "white village",
        "white mountain lakes estates",
        "whitehouse plantation",
        "white cross roads",
        "whitecap",
        "white bushes",
        "white marsh meadows",
        "whitebury",
        "whiteburg",
        "white ball",
        "white bluffs",
        "white oak flat",
        "whitefish station",
        "white plains village",
        "whites store",
        "whitemouth",
        "whiteoak springs (historical)",
        "whiteway terrace",
        "white birch estates mobile home park",
        "whiteburn mines",
        "white house park",
        "whitewater estates",
        "whitefish lake",
        "white tank",
        "white water park",
        "white haven center",
        "whiteoak flats",
        "white oak (historical)",
        "whites cross",
        "white canyon (historical)",
        "whitehouse",
        "white level",
        "whitesville",
        "whites addition",
        "whitetree",
        "whiteville",
        "mary e white estate",
        "fort white",
        "whitepost",
        "whitehall corners",
        "whitehall manor",
        "white pine acres",
        "camp marion white",
        "white bird mobile home park",
        "whitehouse landing",
        "white horn",
        "north whitefield",
        "white mwandi",
        "whitemarsh green",
        "white oak cliffs",
        "whiteley",
        "whitecliffs",
        "bob white",
        "white hall (historical)",
        "upper whitehead",
        "whitehill",
        "whitehorn",
        "white womans town (historical)",
        "white butte",
        "white addition",
        "white mills",
        "white pines trailer park",
        "white horse village",
        "whites crossroads",
        "bobwhite (historical)",
        "white place",
        "whiteman",
        "the coves at white trout lake",
        "whitebridge",
        "white flint springs",
        "white oak farms",
        "whites creek west",
        "white marsh estates",
        "whitethorne",
        "west whitesburg (historical)",
        "whitewater",
        "whitelaw",
        "whitemarsh",
        "white gate",
        "whitehouse station",
        "whitemarsh island",
        "white harbor",
        "whiteoak",
        "whitesboro-burleigh",
        "whites flat",
        "whitewood grove",
        "bob white fork",
        "whiteland crest",
        "white cloud mobile home park",
        "whiteface",
        "white hall estates",
        "white castle",
        "north white plains",
        "white bear beach",
        "whiteside corners",
        "white eagle",
        "white hawk",
        "whites creek springs (historical)",
        "white rock hill",
        "white hall",
        "white oak meadows",
        "whiteville park",
        "whiteoak creek subdivision",
        "white bear",
        "white hat landing",
        "white river estates",
        "white oak springs (historical)",
        "whitefish bay",
        "whitefields",
        "white oak falls",
        "white oak bottom",
        "white oak trailer park",
        "whitebread",
        "mount white",
        "white mills junction",
        "whitebreast",
        "mount whitestone",
        "whites cross roads (historical)",
        "white river (historical)",
        "white house heights",
        "white stone",
        "the manors at white trout lake",
        "village of white oak",
        "white oak estates mobile home park",
        "white river estate mobile home park",
        "whitecroft",
        "white plains",
        "white knob (historical)",
        "east whitehall",
        "whitefield (historical)",
        "whiteland",
        "white river city",
        "white terrace",
        "white spot",
        "whites village",
        "white plantation",
        "whitehawk",
        "whitebead",
        "white bird",
        "white plains mobile home park",
        "white shed",
        "white shield",
        "whiterock",
        "white (historical)",
        "white banks",
        "whitechurch",
        "white creek country estates mobile home park",
        "whiteford hollow",
        "whitehurst",
        "white lake",
        "white roding",
        "whitemud creek",
        "white city subdivision number 2",
        "whites mills",
        "upper white oak creek (historical)",
        "white oak manor",
        "white oak ridge (historical)",
        "white rock colony",
        "whitestown",
        "whiteabbey",
        "whites creek",
        "white salmon",
        "whitethorn",
        "white rocks",
        "whites (historical)",
        "manderson-white horse creek",
        "white head",
        "white cloud",
        "white rapids",
        "whitehall township",
        "white oak east",
        "white sulphur springs",
        "white station",
        "whiteys corner hut",
        "whitefoord",
        "lower whitehead",
        "whitemore",
        "cappagh white",
        "whiteclay",
        "white city subdivision number 1",
        "white creek manor",
        "white house trailer park",
        "white wing",
        "whites creek east",
        "white trout lake shores",
        "point white",
        "the white cross",
        "owen white plat",
        "little white oak",
        "white acres",
        "whiteway",
        "whitestone village",
        "white rose",
        "white pine mobile home park",
        "white path",
        "white apple",
        "east white plains",
        "white oak west",
        "white crossroads",
        "whitehouse upper",
        "white gun",
        "whitemarsh estates",
        "white plains crossroad",
        "white oak crest",
        "center white creek",
        "fort riley-camp whiteside",
        "whitehall",
        "whitehall terrace",
        "white trout estate",
        "analea white hall",
        "west white plains",
        "whitecommons",
        "whites town",
        "white horse beach",
        "white oak park",
        "white house springs",
        "whitehead crossroads",
        "white swan",
        "whiteleysburg",
        "satterwhite",
        "white pine",
        "white hill estates",
        "whitewood",
        "white oaks estates mobile home park",
        "white horse heights",
        "old white hall (historical)",
        "white gum valley",
        "whitestone",
        "whiteston",
        "whitesboro",
        "white corners",
        "whitehall estates",
        "whites mountain",
        "white horses",
        "white haven",
        "white store",
        "white horse",
        "white city",
        "whitestone point",
        "white earth",
        "white house acres",
        "white pump",
        "white tower",
        "south whiteville",
        "white horse farm",
        "whitewood estates",
        "white hollow",
        "white oak run"
    ]
    trie_obj = pygtrie.CharTrie()
    trie_obj = load_trie_obj(trie_obj, words)
    print match_names(test_word, trie_obj)